### ISSUE TITLE
Bug: A syllable shouldn't preceded a Cluster with a Shureq

### ISSUE THREAD

**Issue by rivkahcarl** [charlesLoder/hebraisch-umschrift#2]
Believe this bug might have creeped into the Umschrift project as well. Feel free to move or delete ticket as you need. 

<img width="1028" alt="Screen Shot 2020-10-22 at 1 27 40 PM" src="https://user-images.githubusercontent.com/3063909/96859902-c0488880-146a-11eb-98ed-a74c0295aff8.png">

**Comment by charlesLoder** [comment]
Just forgot to update havarotjs package within umschrift. All should be up to date now. Let me know if you still get that error.
